apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - image: gcr.io/gke-project-181000/rails_app:latest
          name: web
          env:
            - name: RAILS_DB_HOST
              value: 127.0.0.1
            - name: RAILS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: RAILS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: RAILS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-password
                  key: password
            - name: SECRET_KEY_BASE
              value: 'hoge'
            - name: RAILS_ENV
              value: production
            - name: RACK_ENV
              value: production
          ports:
            - containerPort: 3000
              name: testapp
          volumeMounts:
            - mountPath: /myapp/public
              name: web-assets
            - mountPath: /myapp/tmp/sockets
              name: web-sock
        - image: b.gcr.io/cloudsql-docker/gce-proxy:1.05
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=gke-project-181000:asia-east1:mysql-1=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
        - image: gcr.io/gke-project-179823/nginx:latest
          name: nginx
          ports:
            - name: http-server
              containerPort: 80
            - name: https-server
              containerPort: 443
          volumeMounts:
            - mountPath: /myapp/public
              name: web-assets
              readOnly: true
            - mountPath: /myapp/tmp/sockets
              name: web-sock
      volumes:
        - name: web-assets
          emptyDir: {}
        - name: web-sock
          emptyDir: {}
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs